### ISSUE TITLE
EOY Report getting a problem with Highcharts and generating content.

### ISSUE THREAD

**Issue by mabbettbyron** [mahalsnz/terraprobe#245]
For  WynFruit API pulls correct data.
https://terraprobe.mahal.co.nz/graphs/api/v1/eoy_farm_report/82/3/1128/

However when generating charts getting some JS errors.

Uncaught TypeError: Cannot read properties of undefined (reading 'drawRectangle')
    at highcharts-more.js:167:96
    at A (highcharts-more.js:8:338)
    at highcharts-more.js:164:407
    at highcharts-more.js:8:222
    at highcharts-more.js:8:276
solid-gauge.src.js:564 Uncaught TypeError: Cannot read properties of undefined (reading 'drawRectangle')
    at solid-gauge.js:18:329
    at f (solid-gauge.js:10:371)
    at solid-gauge.js:13:442
    at solid-gauge.js:10:255
    at solid-gauge.js:10:309
highcharts.min.js:1 Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=solidgauge
 - missingModuleFor: solidgauge
    at Object.<anonymous> (highcharts.min.js:1:2079)
    at v (highcharts.min.js:1:4442)
    at l (highcharts.min.js:1:2002)
    at Q.initSeries (highcharts.min.js:1:177464)
    at highcharts.min.js:1:192850
    at Array.forEach (<anonymous>)
    at Q.firstRender (highcharts.min.js:1:192828)
    at Q.<anonymous> (highcharts.min.js:1:177332)
    at v (highcharts.min.js:1:4442)
    at Q.init (highcharts.min.js:1:176591)

**Comment by mabbettbyron** [comment]
Done 2 hours. Still to deliver in weekend.

**Comment by mabbettbyron** [comment]
Done.
